### ISSUE TITLE
.github files

### ISSUE THREAD

**Issue by Kleissner** [PeernetOfficial/core#62]
@Akilan1999 what's the benefit/use of the files in the https://github.com/PeernetOfficial/core/tree/master/.github folder?
Is it for creating automated releases? I like the idea in general, but since core is a library and not a standalone program, not sure how much sense automated release make here.

**Comment by Akilan1999** [comment]
.github files store anything related to github actions. This could be to create CI test before merging a PR. In this case it's only storing the automatic Releaser.
